[project]
name = "celebv-hq"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "opencv-python>=4.11.0.86",
    "youtube-dl>=2021.12.17",
]
